### ISSUE TITLE
Help Needed: sheriff.config Rules Not Enforcing as Expected

### ISSUE THREAD

**Issue by alcaidio** [softarc-consulting/sheriff#117] opened 2024-08-23 08:45 UTC
I thought this was the best place to post my issue after [stackoverflow](https://stackoverflow.com/questions/78905037/why-arent-violations-with-sheriff-triggering-errors-help-needed-sheriff-conf). 

I'm having trouble understanding why I don't get an error when the rules defined in sheriff.config are violated. For example, when placing a component from one domain into another, or placing a feature component in the ui or util folders.

Here is my sheriff.config:

```
export const config: SheriffConfig = {
  version: 1,
  entryFile: 'src/main.ts',
  tagging: {
    src: {
      app: {
        'domains/<domain>': {
          '<type>/*': ['domain:<domain>', 'type:<type>'],
        },
        'shared/<type>/*': ['domain:shared', 'type:<type>'],
        'openapi/<domain>/*': ['domain:<domain>', 'type:util'],
      },
      environments: ['domain:shared', 'type:util'],
    },
  },
  depRules: {
    root: ['*'],
    'domain:*': [sameTag, 'domain:shared'],
    'type:feature': [
      ({ to }) => to.startsWith('type:ui'),
      'type:data',
      'type:util',
    ],
    'type:ui': ['type:data', 'type:util'],
    'type:data': ['type:util'],
    'type:util': noDependencies,
  },
};
```

And here is the a partial output of npx sheriff list command:

```
. (root)
└── src
  ├── app
    ├── domains
      ├── device
        ├── data (domain:device, type:data)
        ├── feature (domain:device, type:feature)
          ├── default-parameters (domain:device, type:feature/default-parameters)
          └── tracker-details (domain:device, type:feature/tracker-details)
        ├── ui (domain:device, type:ui)
        └── util (domain:device, type:util)
      └── gateway
        ├── data (domain:gateway, type:data)
        ├── feature (domain:gateway, type:feature)
          └── gateway-details (domain:gateway, type:feature/gateway-details)
        ├── ui (domain:gateway, type:ui)
        └── util (domain:gateway, type:util)
    ├── openapi
      ├── gateway (domain:gateway, type:util)
        ├── api (domain:gateway/api, type:util)
        └── model (domain:gateway/model, type:util)
    └── shared
      ├── data (domain:shared, type:data)
      ├── feature (domain:shared, type:feature)
      ├── ui (domain:shared, type:ui)
        ├── card (domain:shared, type:ui/card)
      └── util (domain:shared, type:util)
  └── environments (domain:shared, type:util)

```
Here's the output of npx sheriff verify:

Verification Report :

`No issues found. Well done!`

Even if i dont respect the config...

I'm not sure how to resolve this issue. Does anyone have any ideas?

**Comment by rainerhahnekamp** [comment] 2024-08-23 09:46
It would be great to have a working example, but since you've already posted the config, it is enough if you take the file in question and post its path and its import statements.

**Comment by rainerhahnekamp** [comment] 2024-08-25 09:32
Just noticed that you have all your features in one parent folder `feature` which seems to be a module on its own?

Shouldn't it be more like?

```bash
. (root)
└── src
  ├── app
    ├── domains
      ├── device
        ├── data (domain:device, type:data)
        ├── feature
          ├── default-parameters (domain:device, type:feature)
          └── tracker-details (domain:device, type:feature)
```

In that case, your config should look like this:

```typescript
export const config: SheriffConfig = {
  version: 1,
  entryFile: 'src/main.ts',
  tagging: {
    src: {
      app: {
        'domains/<domain>': {
          'feature/<feature>: ['domain:<domain>', 'type:<type>'],
          '<type>': ['domain:<domain>', 'type:<type>'],
        },
        'shared/<type>/*': ['domain:shared', 'type:<type>'],
        'openapi/<domain>/*': ['domain:<domain>', 'type:util'],
      },
      environments: ['domain:shared', 'type:util'],
    },
  },
  depRules: {
    // ...
  },
};
```

**Comment by alcaidio** [comment] 2024-08-26 13:30
> Just noticed that you have all your features in one parent folder `feature` which seems to be a module on its own?
> 
> Shouldn't it be more like?
> 
> ```shell
> . (root)
> └── src
>   ├── app
>     ├── domains
>       ├── device
>         ├── data (domain:device, type:data)
>         ├── feature
>           ├── default-parameters (domain:device, type:feature)
>           └── tracker-details (domain:device, type:feature)
> ```
> 
> In that case, your config should look like this:
> 
> ```ts
> export const config: SheriffConfig = {
>   version: 1,
>   entryFile: 'src/main.ts',
>   tagging: {
>     src: {
>       app: {
>         'domains/<domain>': {
>           'feature/<feature>: ['domain:<domain>', 'type:<type>'],
>           '<type>': ['domain:<domain>', 'type:<type>'],
>         },
>         'shared/<type>/*': ['domain:shared', 'type:<type>'],
>         'openapi/<domain>/*': ['domain:<domain>', 'type:util'],
>       },
>       environments: ['domain:shared', 'type:util'],
>     },
>   },
>   depRules: {
>     // ...
>   },
> };
> ```

Yes here a screenshot
![Screenshot from 2024-08-26 15-28-54](https://github.com/user-attachments/assets/8bb44d87-d842-46a6-bcac-1530b7c6e659)

**Comment by alcaidio** [comment] 2024-08-26 13:40
> It would be great to have a working example, but since you've already posted the config, it is enough if you take the file in question and post its path and its import statements.

For instance here i import a component from an other domain (DDSComponent)
![Screenshot from 2024-08-26 15-39-11](https://github.com/user-attachments/assets/21420a14-fdef-4c57-863d-0c99433f47d4)

**Comment by rainerhahnekamp** [comment] 2024-08-26 13:41
@alcaidio  Okay, in which folder is this file located?

**Comment by rainerhahnekamp** [comment] 2024-08-26 13:51
@alcaidio I encountered a similar issue last week but wasn't sure if it was a bug or misconfiguration. I'll investigate and mark this issue as "potential bug" until further notice.

**Comment by rainerhahnekamp** [comment] 2024-08-28 19:00
@alcaidio, I encountered a bug which might be related to your reported issue. Fix will come coon.

**Comment by rainerhahnekamp** [comment] 2024-09-02 14:25
@alcaidio, can you please try it out with v0.17.0? I can confirm that the new dependency rules algorithm works on a really project and I hope that it was the cause of your issue.

**Comment by alcaidio** [comment] 2024-09-03 07:28
@rainerhahnekamp i try with 
```
@softarc/eslint-plugin-sheriff": "^0.17.0",
@softarc/sheriff-core": "^0.17.0",
```
But nothing change, i always can import component from a domain to another :/

**Comment by hoangvutruong513** [comment] 2024-09-03 18:53
Hello @rainerhahnekamp, @alcaidio. 

I think I actually encountered this issue before, where Sheriff was unable to flag a forbidden module import as a Lint error.

I notice that in @alcaidio screenshot, the full path `src/app/...` is being used to import modules.

As weird as this may sounds:

1. This error happens when I was importing modules using the full import path, e.g. `src/app/path/to/forbidden/module`, like @alcaidio is doing. In this case, Sheriff is unable to flag the import as `forbidden`.

2. The error is gone, when I switch to using relative path to import modules, e.g. `../../../path/to/forbidden/module`. In this case, Sheriff is able to flag the import as forbidden due to insufficient dependency rules.

3. The error is also gone, when I use path substitution in `tsconfig.json` to import modules. Basically in `tsconfig.json`:
```json
{
  "compilerOptions": {
    // other configs
    "paths": {
      "@subs/*":  ["src/app/*"]
    }
}
```
Then in your code, use `@subs/path/to/forbidden/module`. Sheriff would be able to flag that this is a forbidden import.

I am unable to share screenshots due to company policy, but I hope the above info is enough for @rainerhahnekamp to do a bug re-production.

@alcaidio may be you can try switching your import paths to option (2) or (3) above and see if your problem is fixed.

I am using Sheriff version 0.16 by the way.

**Comment by rainerhahnekamp** [comment] 2024-09-03 19:01
@hoangvutruong513 thanks for that tip.

It could be that these absolute imports couldn't be properly resolved. In case that happens, Sheriff silently skips them because they should throw a TypeScript compilation error either way.

Thanks, maybe there is connection to #122

I will investigate further

**Comment by rainerhahnekamp** [comment] 2024-09-16 21:03
@hoangvutruong513 @alcaidio v0.17.2 can now also deal with static imports. Please give it a try and let me know if it works. Thank you

**Comment by hoangvutruong513** [comment] 2024-09-23 15:20
> @hoangvutruong513 @alcaidio v0.17.2 can now also deal with static imports. Please give it a try and let me know if it works. Thank you

Hello @rainerhahnekamp, I just tested v0.17.3, glad to report that the issue I reported has been resolved. Now Sheriff correctly raised lint errors, regardless of the format of the import path (absolute/substituted/relative paths).

Although the update to the core dependency logic introduced in v0.17.2 has led to new dependency errors in my codebase. 

After reading the doc, am I correct to say that ALL `from` tags need to satisfy ANY `to` tags in order for the lint rule to pass?

Thank you again for this amazing library. Kudos to the new documentation too.

**Comment by rainerhahnekamp** [comment] 2024-09-23 16:05
I am so glad to hear that. We had integration tests set up, but the final test is still done by someone else.

You are right about the new rules. The algorithm loops over the from tags and every from tag requires a clearance.

0.17.0 introduced these changes, which could lead to new dependency errors. The reason was to streamline it to the way how Nx is doing it.

Thanks a lot, @hoangvutruong513. If you encounter other issues, let us know. Of course, the same goes for you, @alcaidio.

Going to close this issue now.

**Closed by rainerhahnekamp** 2024-09-23 16:05 UTC
Labels: bug
